import './globals.css'
import Nav from '../components/Nav'
import Providers from './Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-sky-950'>
        
        <main className='pt-8'>
        <Providers>
        <Nav></Nav>
        {children}
        </Providers>
        
        </main>
        
      </body>
    </html>
  )
}
